Fixed a bug with exception handling during ``_create_process`` calls.
